/**
 * Mock torrent data for preview/demo mode.
 * This file is ONLY included in preview builds (BUILD_MODE=demo).
 * Production builds never reference this file.
 */

import { Status } from "rpc/transmission";
import type { Torrent } from "rpc/torrent";
import type { SessionInfo } from "rpc/client";

export const mockTorrents: Torrent[] = [
    {
        id: 1,
        name: "Ubuntu 24.04 LTS Desktop amd64.iso",
        status: Status.downloading,
        percentDone: 0.672,
        sizeWhenDone: 5800000000,
        haveValid: 3897600000,
        rateDownload: 4521000,
        rateUpload: 128000,
        uploadRatio: 0.12,
        eta: 2160,
        addedDate: Date.now() / 1000 - 86400,
        doneDate: 0,
        queuePosition: 0,
        labels: ["系统"],
        downloadDir: "/data/downloads",
        error: 0,
        errorString: "",
        trackerStats: [
            { host: "tracker.ubuntu.com", hasAnnounced: true, lastAnnounceSucceeded: true, lastAnnounceResult: "Success", announceState: 1, seederCount: 320, leecherCount: 45 },
        ],
        peers: [],
        bandwidthPriority: 0,
        seedRatioLimit: 2,
        seedRatioMode: 0,
        seedIdleLimit: 30,
        seedIdleMode: 0,
        cachedError: "",
        cachedTrackerStatus: "工作",
        cachedMainTracker: "ubuntu.com",
        cachedSeedsTotal: 320,
        cachedPeersTotal: 45,
    },
    {
        id: 2,
        name: "三体全集（精装版）.epub",
        status: Status.seeding,
        percentDone: 1,
        sizeWhenDone: 2500000,
        haveValid: 2500000,
        rateDownload: 0,
        rateUpload: 34200,
        uploadRatio: 5.8,
        eta: 0,
        addedDate: Date.now() / 1000 - 604800,
        doneDate: Date.now() / 1000 - 500000,
        queuePosition: 1,
        labels: ["书籍"],
        downloadDir: "/data/books",
        error: 0,
        errorString: "",
        trackerStats: [
            { host: "tracker.example.com", hasAnnounced: true, lastAnnounceSucceeded: true, lastAnnounceResult: "Success", announceState: 3, seederCount: 88, leecherCount: 12 },
        ],
        peers: [],
        bandwidthPriority: 0,
        seedRatioLimit: 2,
        seedRatioMode: 0,
        seedIdleLimit: 30,
        seedIdleMode: 0,
        cachedError: "",
        cachedTrackerStatus: "工作(上传中)",
        cachedMainTracker: "example.com",
        cachedSeedsTotal: 88,
        cachedPeersTotal: 12,
    },
    {
        id: 3,
        name: "Black Myth Wukong v1.1.2.zip",
        status: Status.stopped,
        percentDone: 0.35,
        sizeWhenDone: 35000000000,
        haveValid: 12250000000,
        rateDownload: 0,
        rateUpload: 0,
        uploadRatio: 0,
        eta: 0,
        addedDate: Date.now() / 1000 - 172800,
        doneDate: 0,
        queuePosition: 2,
        labels: ["游戏"],
        downloadDir: "/data/games",
        error: 0,
        errorString: "",
        trackerStats: [
            { host: "tracker.gametorrents.net", hasAnnounced: true, lastAnnounceSucceeded: true, lastAnnounceResult: "Success", announceState: 0, seederCount: 15, leecherCount: 200 },
        ],
        peers: [],
        bandwidthPriority: 0,
        seedRatioLimit: 2,
        seedRatioMode: 0,
        seedIdleLimit: 30,
        seedIdleMode: 0,
        cachedError: "",
        cachedTrackerStatus: "",
        cachedMainTracker: "gametorrents.net",
        cachedSeedsTotal: 15,
        cachedPeersTotal: 200,
    },
    {
        id: 4,
        name: "【蓝光】流浪地球2 REMUX-2160p-TrueHD.mkv",
        status: Status.downloading,
        percentDone: 0.89,
        sizeWhenDone: 62000000000,
        haveValid: 55180000000,
        rateDownload: 12500000,
        rateUpload: 890000,
        uploadRatio: 0.05,
        eta: 540,
        addedDate: Date.now() / 1000 - 3600,
        doneDate: 0,
        queuePosition: 3,
        labels: ["影视"],
        downloadDir: "/data/movies",
        error: 0,
        errorString: "",
        trackerStats: [
            { host: "tracker.mteam.org", hasAnnounced: true, lastAnnounceSucceeded: true, lastAnnounceResult: "Success", announceState: 1, seederCount: 42, leecherCount: 68 },
            { host: "tracker.pterclub.com", hasAnnounced: true, lastAnnounceSucceeded: true, lastAnnounceResult: "Success", announceState: 1, seederCount: 35, leecherCount: 50 },
        ],
        peers: [],
        bandwidthPriority: 0,
        seedRatioLimit: 2,
        seedRatioMode: 0,
        seedIdleLimit: 30,
        seedIdleMode: 0,
        cachedError: "",
        cachedTrackerStatus: "工作",
        cachedMainTracker: "mteam.org",
        cachedSeedsTotal: 42,
        cachedPeersTotal: 68,
    },
    {
        id: 5,
        name: "Fedora-Server-dvd-x86_64-40.iso",
        status: Status.stopped,
        percentDone: 1,
        sizeWhenDone: 8700000000,
        haveValid: 8700000000,
        rateDownload: 0,
        rateUpload: 0,
        uploadRatio: 1.2,
        eta: 0,
        addedDate: Date.now() / 1000 - 432000,
        doneDate: Date.now() / 1000 - 400000,
        queuePosition: 4,
        labels: ["系统"],
        downloadDir: "/data/downloads",
        error: 0,
        errorString: "",
        trackerStats: [
            { host: "tracker.fedoraproject.org", hasAnnounced: true, lastAnnounceSucceeded: true, lastAnnounceResult: "Success", announceState: 0, seederCount: 120, leecherCount: 30 },
        ],
        peers: [],
        bandwidthPriority: 0,
        seedRatioLimit: 2,
        seedRatioMode: 0,
        seedIdleLimit: 30,
        seedIdleMode: 0,
        cachedError: "",
        cachedTrackerStatus: "",
        cachedMainTracker: "fedoraproject.org",
        cachedSeedsTotal: 120,
        cachedPeersTotal: 30,
    },
    {
        id: 6,
        name: "Debian 12 netinst",
        status: Status.seeding,
        percentDone: 1,
        sizeWhenDone: 640000000,
        haveValid: 640000000,
        rateDownload: 0,
        rateUpload: 56000,
        uploadRatio: 12.5,
        eta: 0,
        addedDate: Date.now() / 1000 - 1209600,
        doneDate: Date.now() / 1000 - 1100000,
        queuePosition: 5,
        labels: ["系统"],
        downloadDir: "/data/downloads",
        error: 0,
        errorString: "",
        trackerStats: [
            { host: "tracker.debian.org", hasAnnounced: true, lastAnnounceSucceeded: true, lastAnnounceResult: "Success", announceState: 3, seederCount: 500, leecherCount: 10 },
        ],
        peers: [],
        bandwidthPriority: 0,
        seedRatioLimit: 2,
        seedRatioMode: 0,
        seedIdleLimit: 30,
        seedIdleMode: 0,
        cachedError: "",
        cachedTrackerStatus: "工作(上传中)",
        cachedMainTracker: "debian.org",
        cachedSeedsTotal: 500,
        cachedPeersTotal: 10,
    },
    {
        id: 7,
        name: "Private-Tracker-Movie.mkv",
        status: Status.stopped,
        percentDone: 0.42,
        sizeWhenDone: 15000000000,
        haveValid: 6300000000,
        rateDownload: 0,
        rateUpload: 0,
        uploadRatio: 0,
        eta: 0,
        addedDate: Date.now() / 1000 - 259200,
        doneDate: 0,
        queuePosition: 6,
        labels: ["影视", "私有"],
        downloadDir: "/data/movies",
        error: 2,
        errorString: "Tracker returned error",
        trackerStats: [
            { host: "tracker.private.site", hasAnnounced: true, lastAnnounceSucceeded: false, lastAnnounceResult: "Not registered", announceState: 0, seederCount: 0, leecherCount: 0 },
        ],
        peers: [],
        bandwidthPriority: 0,
        seedRatioLimit: 2,
        seedRatioMode: 0,
        seedIdleLimit: 30,
        seedIdleMode: 0,
        cachedError: "Tracker: Not registered",
        cachedTrackerStatus: "Not registered",
        cachedMainTracker: "private.site",
        cachedSeedsTotal: 0,
        cachedPeersTotal: 0,
    },
    {
        id: 8,
        name: "archlinux-2024.08.01-x86_64.iso",
        status: Status.downloading,
        percentDone: 0.12,
        sizeWhenDone: 920000000,
        haveValid: 110400000,
        rateDownload: 2100000,
        rateUpload: 45000,
        uploadRatio: 0,
        eta: 420,
        addedDate: Date.now() / 1000 - 300,
        doneDate: 0,
        queuePosition: 7,
        labels: ["系统"],
        downloadDir: "/data/downloads",
        error: 0,
        errorString: "",
        trackerStats: [
            { host: "tracker.archlinux.org", hasAnnounced: true, lastAnnounceSucceeded: true, lastAnnounceResult: "Success", announceState: 1, seederCount: 200, leecherCount: 25 },
        ],
        peers: [],
        bandwidthPriority: 0,
        seedRatioLimit: 2,
        seedRatioMode: 0,
        seedIdleLimit: 30,
        seedIdleMode: 0,
        cachedError: "",
        cachedTrackerStatus: "工作",
        cachedMainTracker: "archlinux.org",
        cachedSeedsTotal: 200,
        cachedPeersTotal: 25,
    },
];

export const mockSession: SessionInfo = {
    version: "3.00 (preview)",
    "alt-speed-enabled": false,
    "alt-speed-down": 50,
    "alt-speed-up": 10,
    "speed-limit-down-enabled": false,
    "speed-limit-down": 100,
    "speed-limit-up-enabled": false,
    "speed-limit-up": 50,
    "download-dir": "/data/downloads",
    "download-dir-free-space": 500000000000,
    "rpc-version": 17,
};

export const mockSessionStats = {
    "activeTorrentCount": 3,
    "downloadSpeed": 19161000,
    "uploadSpeed": 1154000,
    "pausedTorrentCount": 3,
    "torrentCount": 8,
    "cumulative-stats": { "downloadedBytes": 0, "filesAdded": 0, "sessionCount": 0, "secondsActive": 0, "uploadedBytes": 0 },
    "current-stats": { "downloadedBytes": 0, "filesAdded": 0, "sessionCount": 0, "secondsActive": 0, "uploadedBytes": 0 },
};
