/**
 * Mock torrent data for preview/demo mode.
 * This file is ONLY included in preview builds (BUILD_MODE=demo).
 * Production builds never reference this file.
 */

import { Status } from "rpc/transmission";
import type { Torrent } from "rpc/torrent";
import type { SessionInfo } from "rpc/client";

function makeId(): string {
    return Array.from({ length: 40 }, () => Math.floor(Math.random() * 16).toString(16)).join("");
}

function makeFiles(count: number, baseName: string, baseSize: number) {
    const files = [];
    for (let i = 0; i < count; i++) {
        files.push({
            name: `${baseName}_part${i + 1}.${baseName.split(".").pop() ?? "dat"}`,
            length: Math.floor(baseSize / count) + Math.floor(Math.random() * 1000),
            bytesCompleted: 0,
        });
    }
    return files;
}

function baseTorrent(overrides: Partial<Torrent>): Torrent {
    const files = overrides.files ?? makeFiles(3, overrides.name ?? "file.dat", overrides.totalSize ?? 1000000);
    return {
        status: Status.stopped,
        percentDone: 0,
        sizeWhenDone: overrides.totalSize ?? 1000000,
        leftUntilDone: overrides.totalSize ?? 1000000,
        haveValid: 0,
        haveUnchecked: 0,
        rateDownload: 0,
        rateUpload: 0,
        uploadRatio: 0,
        eta: 0,
        addedDate: Date.now() / 1000 - 86400,
        doneDate: 0,
        activityDate: Date.now() / 1000 - 100,
        queuePosition: 0,
        labels: [],
        downloadDir: "/data/downloads",
        error: 0,
        errorString: "",
        hashString: makeId(),
        pieceSize: 262144,
        pieceCount: Math.ceil((overrides.totalSize ?? 1000000) / 262144),
        pieces: "",
        comment: "",
        creator: "",
        magnetLink: "",
        group: "",
        downloadedEver: 0,
        uploadedEver: 0,
        corruptEver: 0,
        secondsDownloading: 0,
        secondsSeeding: 0,
        downloadLimited: false,
        uploadLimited: false,
        downloadLimit: 100,
        uploadLimit: 100,
        maxConnectedPeers: 200,
        peersConnected: 0,
        peersSendingToUs: 0,
        peersGettingFromUs: 0,
        recheckProgress: 0,
        metadataPercentComplete: 1,
        dateCreated: 0,
        startDate: 0,
        editDate: 0,
        isFinished: false,
        isPrivate: false,
        isStalled: true,
        desiredAvailable: 0,
        manualAnnounceTime: 0,
        "file-count": files.length,
        "peer-limit": 200,
        honorsSessionLimits: true,
        sequentialDownload: false,
        torrentFile: "",
        "primary-mime-type": "application/octet-stream",
        bandwidthPriority: 0,
        seedRatioLimit: 2,
        seedRatioMode: 0,
        seedIdleLimit: 30,
        seedIdleMode: 0,
        webseedsSendingToUs: 0,
        etaIdle: 0,
        files,
        fileStats: files.map(() => ({ wanted: true, priority: 0 })),
        trackers: [],
        trackerList: "",
        wanted: files.map(() => true),
        priorities: files.map(() => 0),
        peers: [],
        peersFrom: {},
        webseeds: [],
        cachedError: "",
        cachedTrackerStatus: "",
        cachedMainTracker: "",
        cachedSeedsTotal: 0,
        cachedPeersTotal: 0,
        ...overrides,
    } as Torrent;
}

export const mockTorrents: Torrent[] = [
    baseTorrent({
        id: 1,
        name: "Ubuntu 24.04 LTS Desktop amd64.iso",
        status: Status.downloading,
        percentDone: 0.672,
        totalSize: 5800000000,
        leftUntilDone: 1902400000,
        haveValid: 3897600000,
        rateDownload: 4521000,
        rateUpload: 128000,
        uploadRatio: 0.12,
        eta: 2160,
        addedDate: Date.now() / 1000 - 86400,
        labels: ["系统"],
        downloadDir: "/data/downloads",
        comment: "Ubuntu 24.04 LTS Noble Numbat",
        pieceSize: 262144,
        pieceCount: 22119,
        files: makeFiles(2, "ubuntu-24.04-desktop-amd64.iso", 5800000000),
        trackers: [
            { id: 1, host: "tracker.ubuntu.com", announce: "http://tracker.ubuntu.com:6969/announce", seederCount: 320, leecherCount: 45 },
        ],
        trackerStats: [
            { host: "tracker.ubuntu.com", hasAnnounced: true, lastAnnounceSucceeded: true, lastAnnounceResult: "Success", announceState: 1, seederCount: 320, leecherCount: 45 },
        ],
        peers: [],
        peersConnected: 12,
        peersSendingToUs: 3,
        peersGettingFromUs: 1,
        secondsDownloading: 3600,
        downloadedEver: 3897600000,
        cachedError: "",
        cachedTrackerStatus: "工作",
        cachedMainTracker: "ubuntu.com",
        cachedSeedsTotal: 320,
        cachedPeersTotal: 45,
    }),
    baseTorrent({
        id: 2,
        name: "三体全集（精装版）.epub",
        status: Status.seeding,
        percentDone: 1,
        totalSize: 2500000,
        leftUntilDone: 0,
        haveValid: 2500000,
        rateDownload: 0,
        rateUpload: 34200,
        uploadRatio: 5.8,
        eta: 0,
        addedDate: Date.now() / 1000 - 604800,
        doneDate: Date.now() / 1000 - 500000,
        labels: ["书籍"],
        downloadDir: "/data/books",
        comment: "刘慈欣 三体全集",
        pieceSize: 262144,
        pieceCount: 10,
        files: makeFiles(1, "三体全集.epub", 2500000),
        trackers: [
            { id: 2, host: "tracker.example.com", announce: "http://tracker.example.com:6969/announce", seederCount: 88, leecherCount: 12 },
        ],
        trackerStats: [
            { host: "tracker.example.com", hasAnnounced: true, lastAnnounceSucceeded: true, lastAnnounceResult: "Success", announceState: 3, seederCount: 88, leecherCount: 12 },
        ],
        peers: [],
        peersConnected: 5,
        peersSendingToUs: 0,
        peersGettingFromUs: 2,
        secondsDownloading: 0,
        secondsSeeding: 500000,
        downloadedEver: 2500000,
        uploadedEver: 14500000,
        cachedError: "",
        cachedTrackerStatus: "工作(上传中)",
        cachedMainTracker: "example.com",
        cachedSeedsTotal: 88,
        cachedPeersTotal: 12,
    }),
    baseTorrent({
        id: 3,
        name: "Black Myth Wukong v1.1.2.zip",
        status: Status.stopped,
        percentDone: 0.35,
        totalSize: 35000000000,
        leftUntilDone: 22750000000,
        haveValid: 12250000000,
        rateDownload: 0,
        rateUpload: 0,
        uploadRatio: 0,
        eta: 0,
        addedDate: Date.now() / 1000 - 172800,
        labels: ["游戏"],
        downloadDir: "/data/games",
        comment: "Black Myth Wukong v1.1.2",
        pieceSize: 262144,
        pieceCount: 133493,
        files: makeFiles(8, "Black Myth Wukong.dat", 35000000000),
        trackers: [
            { id: 3, host: "tracker.gametorrents.net", announce: "http://tracker.gametorrents.net:6969/announce", seederCount: 15, leecherCount: 200 },
        ],
        trackerStats: [
            { host: "tracker.gametorrents.net", hasAnnounced: true, lastAnnounceSucceeded: true, lastAnnounceResult: "Success", announceState: 0, seederCount: 15, leecherCount: 200 },
        ],
        peers: [],
        peersConnected: 0,
        peersSendingToUs: 0,
        peersGettingFromUs: 0,
        downloadedEver: 12250000000,
        cachedError: "",
        cachedTrackerStatus: "",
        cachedMainTracker: "gametorrents.net",
        cachedSeedsTotal: 15,
        cachedPeersTotal: 200,
    }),
    baseTorrent({
        id: 4,
        name: "【蓝光】流浪地球2 REMUX-2160p-TrueHD.mkv",
        status: Status.downloading,
        percentDone: 0.89,
        totalSize: 62000000000,
        leftUntilDone: 6820000000,
        haveValid: 55180000000,
        rateDownload: 12500000,
        rateUpload: 890000,
        uploadRatio: 0.05,
        eta: 540,
        addedDate: Date.now() / 1000 - 3600,
        labels: ["影视"],
        downloadDir: "/data/movies",
        comment: "流浪地球2 The Wandering Earth II 2023 REMUX 2160p",
        pieceSize: 524288,
        pieceCount: 118103,
        files: makeFiles(1, "流浪地球2.mkv", 62000000000),
        trackers: [
            { id: 4, host: "tracker.mteam.org", announce: "http://tracker.mteam.org:6969/announce", seederCount: 42, leecherCount: 68 },
            { id: 5, host: "tracker.pterclub.com", announce: "http://tracker.pterclub.com:6969/announce", seederCount: 35, leecherCount: 50 },
        ],
        trackerStats: [
            { host: "tracker.mteam.org", hasAnnounced: true, lastAnnounceSucceeded: true, lastAnnounceResult: "Success", announceState: 1, seederCount: 42, leecherCount: 68 },
            { host: "tracker.pterclub.com", hasAnnounced: true, lastAnnounceSucceeded: true, lastAnnounceResult: "Success", announceState: 1, seederCount: 35, leecherCount: 50 },
        ],
        peers: [],
        peersConnected: 15,
        peersSendingToUs: 8,
        peersGettingFromUs: 2,
        secondsDownloading: 3000,
        downloadedEver: 55180000000,
        cachedError: "",
        cachedTrackerStatus: "工作",
        cachedMainTracker: "mteam.org",
        cachedSeedsTotal: 42,
        cachedPeersTotal: 68,
    }),
    baseTorrent({
        id: 5,
        name: "Fedora-Server-dvd-x86_64-40.iso",
        status: Status.stopped,
        percentDone: 1,
        totalSize: 8700000000,
        leftUntilDone: 0,
        haveValid: 8700000000,
        rateDownload: 0,
        rateUpload: 0,
        uploadRatio: 1.2,
        eta: 0,
        addedDate: Date.now() / 1000 - 432000,
        doneDate: Date.now() / 1000 - 400000,
        labels: ["系统"],
        downloadDir: "/data/downloads",
        comment: "Fedora Server 40 DVD",
        pieceSize: 262144,
        pieceCount: 33204,
        files: makeFiles(1, "Fedora-Server-dvd-x86_64-40.iso", 8700000000),
        trackers: [
            { id: 6, host: "tracker.fedoraproject.org", announce: "http://tracker.fedoraproject.org:6969/announce", seederCount: 120, leecherCount: 30 },
        ],
        trackerStats: [
            { host: "tracker.fedoraproject.org", hasAnnounced: true, lastAnnounceSucceeded: true, lastAnnounceResult: "Success", announceState: 0, seederCount: 120, leecherCount: 30 },
        ],
        peers: [],
        peersConnected: 0,
        downloadedEver: 8700000000,
        uploadedEver: 10440000000,
        cachedError: "",
        cachedTrackerStatus: "",
        cachedMainTracker: "fedoraproject.org",
        cachedSeedsTotal: 120,
        cachedPeersTotal: 30,
    }),
    baseTorrent({
        id: 6,
        name: "Debian 12 netinst",
        status: Status.seeding,
        percentDone: 1,
        totalSize: 640000000,
        leftUntilDone: 0,
        haveValid: 640000000,
        rateDownload: 0,
        rateUpload: 56000,
        uploadRatio: 12.5,
        eta: 0,
        addedDate: Date.now() / 1000 - 1209600,
        doneDate: Date.now() / 1000 - 1100000,
        labels: ["系统"],
        downloadDir: "/data/downloads",
        comment: "Debian 12 bookworm netinst",
        pieceSize: 262144,
        pieceCount: 2442,
        files: makeFiles(1, "debian-12-netinst.iso", 640000000),
        trackers: [
            { id: 7, host: "tracker.debian.org", announce: "http://tracker.debian.org:6969/announce", seederCount: 500, leecherCount: 10 },
        ],
        trackerStats: [
            { host: "tracker.debian.org", hasAnnounced: true, lastAnnounceSucceeded: true, lastAnnounceResult: "Success", announceState: 3, seederCount: 500, leecherCount: 10 },
        ],
        peers: [],
        peersConnected: 2,
        peersSendingToUs: 0,
        peersGettingFromUs: 1,
        secondsDownloading: 0,
        secondsSeeding: 1100000,
        downloadedEver: 640000000,
        uploadedEver: 8000000000,
        cachedError: "",
        cachedTrackerStatus: "工作(上传中)",
        cachedMainTracker: "debian.org",
        cachedSeedsTotal: 500,
        cachedPeersTotal: 10,
    }),
    baseTorrent({
        id: 7,
        name: "Private-Tracker-Movie.mkv",
        status: Status.stopped,
        percentDone: 0.42,
        totalSize: 15000000000,
        leftUntilDone: 8700000000,
        haveValid: 6300000000,
        rateDownload: 0,
        rateUpload: 0,
        uploadRatio: 0,
        eta: 0,
        addedDate: Date.now() / 1000 - 259200,
        labels: ["影视", "私有"],
        downloadDir: "/data/movies",
        comment: "Private Tracker Movie",
        pieceSize: 524288,
        pieceCount: 28614,
        files: makeFiles(1, "Private-Tracker-Movie.mkv", 15000000000),
        trackers: [
            { id: 8, host: "tracker.private.site", announce: "http://tracker.private.site:6969/announce", seederCount: 0, leecherCount: 0 },
        ],
        trackerStats: [
            { host: "tracker.private.site", hasAnnounced: true, lastAnnounceSucceeded: false, lastAnnounceResult: "Not registered", announceState: 0, seederCount: 0, leecherCount: 0 },
        ],
        peers: [],
        peersConnected: 0,
        downloadedEver: 6300000000,
        error: 2,
        errorString: "Tracker returned error",
        cachedError: "Tracker: Not registered",
        cachedTrackerStatus: "Not registered",
        cachedMainTracker: "private.site",
        cachedSeedsTotal: 0,
        cachedPeersTotal: 0,
    }),
    baseTorrent({
        id: 8,
        name: "archlinux-2024.08.01-x86_64.iso",
        status: Status.downloading,
        percentDone: 0.12,
        totalSize: 920000000,
        leftUntilDone: 809600000,
        haveValid: 110400000,
        rateDownload: 2100000,
        rateUpload: 45000,
        uploadRatio: 0,
        eta: 420,
        addedDate: Date.now() / 1000 - 300,
        labels: ["系统"],
        downloadDir: "/data/downloads",
        comment: "Arch Linux 2024.08.01",
        pieceSize: 262144,
        pieceCount: 3510,
        files: makeFiles(1, "archlinux-2024.08.01-x86_64.iso", 920000000),
        trackers: [
            { id: 9, host: "tracker.archlinux.org", announce: "http://tracker.archlinux.org:6969/announce", seederCount: 200, leecherCount: 25 },
        ],
        trackerStats: [
            { host: "tracker.archlinux.org", hasAnnounced: true, lastAnnounceSucceeded: true, lastAnnounceResult: "Success", announceState: 1, seederCount: 200, leecherCount: 25 },
        ],
        peers: [],
        peersConnected: 8,
        peersSendingToUs: 4,
        peersGettingFromUs: 1,
        secondsDownloading: 180,
        downloadedEver: 110400000,
        cachedError: "",
        cachedTrackerStatus: "工作",
        cachedMainTracker: "archlinux.org",
        cachedSeedsTotal: 200,
        cachedPeersTotal: 25,
    }),
];

export const mockSession: SessionInfo = {
    version: "3.00 (preview)",
    "alt-speed-enabled": false,
    "alt-speed-down": 50,
    "alt-speed-up": 10,
    "speed-limit-down-enabled": false,
    "speed-limit-down": 100,
    "speed-limit-up-enabled": false,
    "speed-limit-up": 50,
    "download-dir": "/data/downloads",
    "download-dir-free-space": 500000000000,
    "rpc-version": 17,
};

export const mockSessionStats = {
    "activeTorrentCount": 3,
    "downloadSpeed": 19161000,
    "uploadSpeed": 1154000,
    "pausedTorrentCount": 3,
    "torrentCount": 8,
    "cumulative-stats": { "downloadedBytes": 0, "filesAdded": 0, "sessionCount": 0, "secondsActive": 0, "uploadedBytes": 0 },
    "current-stats": { "downloadedBytes": 0, "filesAdded": 0, "sessionCount": 0, "secondsActive": 0, "uploadedBytes": 0 },
};
