name: 'build'

on:
  workflow_dispatch:
  push:
    tags:
      - v**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  download-dbip:
    runs-on: ubuntu-latest
    steps:
      - name: Download dbip database
        run: |
          YEAR=$(date +%Y)
          MONTH=$(date +%m)
          wget -nv -O- "https://download.db-ip.com/free/dbip-country-lite-${YEAR}-${MONTH}.mmdb.gz" | zcat > dbip.mmdb
      - uses: actions/upload-artifact@v4
        with:
          name: dbip
          path: "dbip.mmdb"

  build-webapp:
    needs: download-dbip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: dbip
          path: src-tauri/

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: install npm packages
        run: npm ci --legacy-peer-deps

      - name: webpack build
        run: npm run webpack-prod

      - name: pack webapp
        working-directory: dist
        id: pack-webapp
        run: |
          GIT_VERSION=`git describe --tags --always`
          zip -9 -r "trguing-web-$GIT_VERSION.zip" ./* -x create\* -x \*.map -x \*flag-icons\*
          echo "ZIPFILE=trguing-web-$GIT_VERSION.zip" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: build web
          path: "dist/${{ steps.pack-webapp.outputs.ZIPFILE }}"

  publish:
    needs: build-webapp
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: build web
          path: artifacts

      # Generate changelog
      - id: prevtag
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo '')
          echo "previous_tag=$PREVIOUS_TAG" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@main
        if: steps.prevtag.outputs.previous_tag
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          show-emoji: false

      - name: 'create release'
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          draft: true
          files: ./artifacts/*
          body: |
            ${{ steps.changelog.outputs.compareurl }}

            ${{ steps.changelog.outputs.changelog }}
